version: "2"

services:
    mariadb:
        image: mariadb:10.0.33
        ports:
         - 3308:3306
        environment:
         - MYSQL_DATABASE=summerb_tests
         - MYSQL_ROOT_PASSWORD=pwd1
        volumes:
         - ./sql_init_scripts:/docker-entrypoint-initdb.d
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        restart: always

    postgres:
        image: postgres:9.6.14
        ports:
         - 5432:5432
        volumes:
         - ./postgre_init_scripts:/docker-entrypoint-initdb.d
        restart: always
        environment:
          - POSTGRES_DB=summerb_tests
          